name: Deploy Backend to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Clonar el repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3) Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4) Lint y tests
      - name: Lint code
        run: npm run lint

      - name: Run unit tests
        run: npm test

      - name: Build project
        run: npm run build

      # 6) Empaquetar backend en ZIP (excluye node_modules, .env y tests)
      - name: Zip backend
        run: |
          rm -f backend.zip
          zip -r backend.zip * .[^.]* -x "node_modules/*" ".env" "tests/*"

      # 7) Desplegar con Publish Profile
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'viba'                               # tu nombre de App Service
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: 'backend.zip'
