name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # 1) exponemos el secret a TODO el job
    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci
        
      - name: Lint code
        run: npm run lint

      - name: Run unit tests
        run: npm test

      # OPCIONAL: para forzar que Vite lo lea como .env.production
      - name: Create .env.production
        run: echo "VITE_API_URL=$VITE_API_URL" > .env.production

      - name: Build frontend
        run: npm run build

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token:                       ${{ secrets.GITHUB_TOKEN }}
          action:                           upload
          app_location:                     /
          api_location:                     ""
          output_location:                  dist
