name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:

      # 1. Clona el repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura Node.js (versión de tu proyecto)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3. Instala dependencias
      - name: Install dependencies
        run: npm ci

      # 4. Construye el frontend
      - name: Build frontend
        run: npm run build
        env:
          VITE_API_URL: "https://viba.azurewebsites.net/api"

      # 5. Despliega a Azure Static Web Apps
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token:                       ${{ secrets.GITHUB_TOKEN }}
          action:                           upload
          app_location:                     /
          api_location:                     ""
          output_location:                  dist
